### ISSUE TITLE
Dimension hopping is broken again - Build #796

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#117]
Changing dimensions (ala mystcraft and twlightforest) isn't loading the chunks until you relog

**Comment by LunNova** [comment]
This should be fixed in build 801 or later.

**Comment by LunNova** [comment]
And if that doesn't work, bb090c5f57a9cd0f9cdbe48b8d9a should fix it.

**Comment by Puremin0rez** [comment]
@nallar 

So it's still broken but in a different way now

Now when I change dimensions, rather then just "sitting" there with nothing loaded - it'll keep bouncing my player up and down over and over again and in the F3 menu it shows my coordinates of where i WOULD be correctly - but it shows i'm in an Ocean biome....

I relog, world loads fine and i'm back in my plains biome.

**Comment by LunNova** [comment]
The patcher may have been patching the wrong method, should be fixed in 2a02f647dedac607a if that was the issue.
If not, mystcraft may be teleporting in its own way instead of using transferPlayerToDimension.

**Comment by Puremin0rez** [comment]
So Dimension hopping is indeed fixed now, however, now I have ANOTHER teleport related problem!

Doing /spawn (via Fihgus Command Mod) often throws me into that rift I described a few comments up - Ocean biome, no chunks load. Need to relog - problem fixed.

**Comment by Puremin0rez** [comment]
So, apparently when I said Dimension hopping is fixed, It only applies to Mystcraft.

Mystcraft books now teleport seamlessy because of the recent fix - but /home and /spawn are still doing what Mystcraft did until you fixed it. Fihgus command mod might need some patching love perhaps?

**Comment by LunNova** [comment]
What does `/ticks e` show in latest after trying to teleport?

**Comment by LunNova** [comment]
This may be fixed-ish with moving chunk sending to the player connection thread. (If that does fix it, it means the player's entity got broken and isn't in any world.)

**Comment by Puremin0rez** [comment]
Still isn't fixed with Fihgus Commands.

/ticks e shows that there is one player when I teleport in the correct dimension, so it's definitely acknowledging I exist.... it just doesn't want to load the chunks :(

As always, relogging will instantly fix it.

Just incase I didn't make this clear, this doesn't happen without TT

**Comment by LunNova** [comment]
Another possible fix in 6bf73e578420

**Comment by Puremin0rez** [comment]
It seems alot better, but it's still happening:
http://i.imgur.com/KlD9pjG.png

**Comment by LunNova** [comment]
2029fcbf1551b622 should fix this - after this, positions seem correct on TP, chunks are loading. Tested with fihgu's `/spawn` between dimensions.

**Comment by LunNova** [comment]
So... apparently that fix [broke stuff](http://i.imgur.com/uEXvsRn.png). That bug should be fixed in 748a10fe7c.

**Comment by Puremin0rez** [comment]
Yes! You fixed it! Thanks alot nallar!

This issue is still happening for some of my dimensions though:
https://github.com/nallar/TickThreading/issues/120

(lets continue this discussion in the other issue)
