### ISSUE TITLE
#1124 Log Spam (Might be related)

### ISSUE THREAD

**Issue by aquagene** [MinimallyCorrect/TickThreading#214]
Great build minus 2 problems. 

With TT, Xycraft keep spamming the server log about multiblocks.
<code>03-16 05:42:21 [INFO] [STDERR] Broken link. Tile at: 519, 68, -3866 did not comprise the multiblock being removed</code>
<code>03-16 05:42:27 [FINE] [XyCraft] Adding MultiBlock: 34739, server</code>
<code>03-16 05:42:27 [FINE] [XyCraft] Deferring MultiBlock: 34740, server</code>
<code>03-16 05:42:31 [INFO] [STDERR] Tile at: 529, 72, -3860 is already joined to multiBlock 34816</code>

 Also, after awhile, no matter what settings I fiddle with, my tickthreaded server will eventually use all the memory (8gb) I give it and crash, even with nobody on. The errors in the log are the same as https://github.com/nallar/TickThreading/issues/210 and https://github.com/nallar/TickThreading/issues/209

**Comment by LunNova** [comment]
Hopefully fixed via 86282ce928f8eea1e46c.

If you still have memory leaks, please make a heap dump when memory usage reaches ~3.5GB, compress it, and PM/email/anything non-publicly send me a link to it.

**Comment by LunNova** [comment]
The log spam is resolved, the memory leak probably is not. I will debug this later - either when jvisualvm finally finishes computing retained sizes in ~forever days - last time I tried it never even completed :/ - or hopefully when YourKit provide an Open Source License. Sorry about the delay.

**Comment by xfloh22** [comment]
hm, also having a problem with some multiblock things. when i add TT the industrial monitors dont show anything. it just shows the blocks and they wont connect. not sure if the problem is related

**Comment by aquagene** [comment]
Awesome to see the xycraft spam fixed, I'll see if I can send you a heap dump of just java. I tested #1147, and I'm not 100% sure, but the memory leak leading to a crash seems to be partially fixed, the memory still rises, but doesn't get high enough to crash the server.

Edit: Crash still occurs after awhile, see https://github.com/nallar/TickThreading/issues/220

**Comment by LunNova** [comment]
Closing this, as the log spam is fixed.
