### ISSUE TITLE
Dynmap Essentials errors

### ISSUE THREAD

**Issue by npdev453** [MinimallyCorrect/TickThreading#216]
12:38:44 [INFO] Loading Player: admin
12:38:45 [INFO] Sending serverside check to: admin
12:38:45 [WARNING] [Essentials] Task #810 for Essentials vDev2.10.68 generated an exception
java.lang.NullPointerException
12:38:56 [WARNING] [dynmap] Bukkit error loading chunk 115,-51 on world
12:38:56 [WARNING] [dynmap] Bukkit error loading chunk 116,-51 on world
12:38:56 [WARNING] [dynmap] Bukkit error loading chunk 117,-51 on world
12:38:56 [WARNING] [dynmap] Bukkit error loading chunk 118,-51 on world
12:38:56 [WARNING] [dynmap] Bukkit error loading chunk 119,-51 on world
12:38:56 [WARNING] [dynmap] Bukkit error loading chunk 120,-51 on world

**Comment by Loonacy** [comment]
I'm getting the same thing with MCPC.

**Comment by LunNova** [comment]
Dynmap error should be fixed in latest.

**Comment by Loonacy** [comment]
I'm using the latest release 1.5 from http://dev.bukkit.org/server-mods/dynmap/files/95-v1-5/

On the changelog it says 
[Forge] Fix exception when ticking unloaded worlds with TickThreading mod active

Still getting errors.

**Comment by LunNova** [comment]
I meant latest tickthreading.

**Comment by Loonacy** [comment]
With the latest TickThreading (1153) and Dynmap 1.5 I'm getting this error once:

2013-03-19 07:58:59 [WARNING] [dynmap] Task #146 for dynmap v1.5-612 generated an exception
java.lang.NullPointerException
    at yc.G(World.java:4613)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getFullTime(CraftWorld.java:519)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getTime(CraftWorld.java:507)
    at org.dynmap.bukkit.BukkitWorld.getTime(Unknown Source)
    at org.dynmap.ClientUpdateComponent.buildClientUpdate(Unknown Source)
    at org.dynmap.ClientUpdateComponent$1.triggered(Unknown Source)
    at org.dynmap.ClientUpdateComponent$1.triggered(Unknown Source)
    at org.dynmap.Event.trigger(Unknown Source)
    at org.dynmap.Events.trigger(Unknown Source)
    at org.dynmap.InternalClientUpdateComponent.writeUpdates(Unknown Source)
    at org.dynmap.InternalClientUpdateComponent$3.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:317)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:249)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at fy.run(ThreadMinecraftServer.java:16)

This error happens every few seconds afterwards:

2013-03-19 07:59:02 [SEVERE] [dynmap] Error while checking world times: 
java.lang.NullPointerException
    at yc.G(World.java:4613)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getFullTime(CraftWorld.java:519)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getTime(CraftWorld.java:507)
    at org.dynmap.bukkit.BukkitWorld.getTime(Unknown Source)
    at org.dynmap.MapManager$CheckWorldTimes$1.call(Unknown Source)
    at org.dynmap.MapManager$CheckWorldTimes$1.call(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:317)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:249)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at fy.run(ThreadMinecraftServer.java:16)
2013-03-19 07:59:07 [SEVERE] [dynmap] Error while checking world times: 
java.lang.NullPointerException
    at yc.G(World.java:4613)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getFullTime(CraftWorld.java:519)
    at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.getTime(CraftWorld.java:507)
    at org.dynmap.bukkit.BukkitWorld.getTime(Unknown Source)
    at org.dynmap.MapManager$CheckWorldTimes$1.call(Unknown Source)
    at org.dynmap.MapManager$CheckWorldTimes$1.call(Unknown Source)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
    at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:317)
    at ho.r(DedicatedServer.java:309)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:249)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
    at fy.run(ThreadMinecraftServer.java:16)

It's a bit spammy, but it doesn't seem to be affecting anything.

**Comment by Loonacy** [comment]
After running the server for a while this error comes back:
 08:28:23 [WARNING] [dynmap] Bukkit error loading chunk 22,-44 on world

**Comment by LunNova** [comment]
Oh, this is because you haven't disabled world unloading in the config, which is required for MCPC+ as MCPC+ doesn't support world unloading.

**Comment by LunNova** [comment]
Reopening, I can fix MCPC+'s world unloading instead of asking people to disable it.

**Comment by LunNova** [comment]
Fixed via c10c1ce306.

**Comment by Loonacy** [comment]
Thanks Nallar, you're awesome!

**Comment by Loonacy** [comment]
Okay, I tested TT build 1163 with MCPC+ build 244/247 and Dynmap 1.5/1.6 and i'm still getting the "error loading chunk" errors.  Dynmap is only rendering around where i'm standing.
EDIT: I also disabled world unloading in the TT config.

**Comment by Loonacy** [comment]
I recompiled Dynmap with a stacktrace printed where the error is and got this:

14:43:19 [WARNING] [dynmap] Bukkit error loading chunk 23,-9 on world
14:43:19 [SEVERE] java.lang.NoSuchFieldError: f
14:43:19 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.CraftWorld.loadChunk(CraftWorld.java:329)
14:43:19 [SEVERE]   at org.dynmap.bukkit.NewMapChunkCache.loadChunks(Unknown Source)
14:43:19 [SEVERE]   at org.dynmap.bukkit.DynmapPlugin$BukkitServer$7.call(Unknown Source)
14:43:19 [SEVERE]   at org.dynmap.bukkit.DynmapPlugin$BukkitServer$7.call(Unknown Source)
14:43:19 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
14:43:19 [SEVERE]   at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
14:43:19 [SEVERE]   at net.minecraft.server.MinecraftServer.spigotTLETick(MinecraftServer.java)
14:43:19 [SEVERE]   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:317)
14:43:19 [SEVERE]   at ho.r(DedicatedServer.java:309)
14:43:19 [SEVERE]   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:249)
14:43:19 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:167)
14:43:19 [SEVERE]   at fy.run(ThreadMinecraftServer.java:16)

**Comment by LunNova** [comment]
Should be fixed in 9f2127b15e13a7fdb0.

**Comment by Loonacy** [comment]
Confirmed working with TT build 1165, MCPC+ build 247 and Dynmap 1.6
