### ISSUE TITLE
Build 408+ - Unhandled exception in worker thread, chunkloader

### ISSUE THREAD

**Issue by gustav9797** [MinimallyCorrect/TickThreading#58]
2013-01-16 16:06:22 [SEVERE] [TickThreading] Unhandled exception in worker thread
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
        at java.util.ArrayList$Itr.next(ArrayList.java:791)
        at codechicken.chunkloader.PlayerChunkViewerManager.calculateChunkChanges(PlayerChunkViewerManager.java:155)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java:40)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:31)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:50)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:255)
        at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:318)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:147)

**Comment by LunNova** [comment]
This should finally be fixed in build 452. Sorry about the delay! :(

**Comment by gustav9797** [comment]
Great!

**Comment by gustav9797** [comment]
Still not fixed, using build 452

2013-01-16 19:33:09 [SEVERE] [TickThreading] Unhandled exception in worker thread
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
        at java.util.ArrayList$Itr.next(ArrayList.java:791)
        at codechicken.chunkloader.PlayerChunkViewerManager.calculateChunkChanges(PlayerChunkViewerManager.java:155)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd_nosynchronize(ChunkLoaderEventHandler.java:40)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:32)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:50)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:255)
        at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:318)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)

**Comment by LunNova** [comment]
Can you try the latest build?

**Comment by gustav9797** [comment]
Using build 456

2013-01-16 20:32:01 [SEVERE] [TickThreading] Unhandled exception in worker thread
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
        at java.util.ArrayList$Itr.next(ArrayList.java:791)
        at codechicken.chunkloader.PlayerChunkViewerManager.calculateChunkChanges_nosynchronize(PlayerChunkViewerManager.java:155)
        at codechicken.chunkloader.PlayerChunkViewerManager.calculateChunkChanges(PlayerChunkViewerManager.java)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd_nosynchronize(ChunkLoaderEventHandler.java:40)
        at codechicken.chunkloader.ChunkLoaderEventHandler.tickEnd(ChunkLoaderEventHandler.java)
        at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:32)
        at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:50)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
        at net.minecraft.server.MinecraftServer.doWorldTick(MinecraftServer.java:255)
        at me.nallar.tickthreading.minecraft.patched.PatchMinecraftServer$TickRunnable.run(PatchMinecraftServer.java:318)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:39)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:150)

**Comment by LunNova** [comment]
/me bangs head against desk

I am so confused! :(

**Comment by LunNova** [comment]
Possibly fixed in the latest build...

**Comment by gustav9797** [comment]
Lets try then! :)

**Comment by gustav9797** [comment]
Nope, still getting the error. This is weird!

**Comment by LunNova** [comment]
Were people using the /chunkloaders command when this happened? If so, 461 may fix it.

**Comment by gustav9797** [comment]
Nope, they never use that command and they didn't know it existed.

**Comment by gustav9797** [comment]
01-17 15:51:25 [SEVERE] [TickThreading] Error patching handleCommand in codechicken.chunkloader.CommandChunkLoaders with synchronize
javassist.CannotCompileException: cannot find codechicken.core.commands.PlayerCommand
        at javassist.CtBehavior.copy(CtBehavior.java:77)
        at javassist.CtMethod.<init>(CtMethod.java:114)
        at javassist.CtNewMethod.copy(CtNewMethod.java:163)
        at me.nallar.tickthreading.patcher.Patches.synchronize(Patches.java:368)
        at me.nallar.tickthreading.patcher.Patches.synchronize(Patches.java:346)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:307)
        at me.nallar.tickthreading.patcher.PatchManager$PatchMethodDescriptor.run(PatchManager.java:280)
        at me.nallar.tickthreading.patcher.PatchManager.runPatches(PatchManager.java:195)
        at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:79)
        at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:27)
Caused by: javassist.NotFoundException: codechicken.core.commands.PlayerCommand
        at javassist.ClassPool.get(ClassPool.java:450)
        at javassist.CtClassType.getSuperclass(CtClassType.java:706)
        at javassist.CtBehavior.copy(CtBehavior.java:58)
        ... 12 more

**Comment by LunNova** [comment]
So that's why those fixes don't work - the code which doesn't work is in a coremod, and TT doesn't patch coremods. Yet. ;)

**Comment by gustav9797** [comment]
Well this spams the console and logs and everything. I can't uninstall chickenchunks either, tried all possible ways. It just gives me an error.

**Comment by LunNova** [comment]
I will get it fixed, just maybe not today. Currently lying in bed, hoping I
don't throw up again, so I'm not really able to code.

**Comment by LunNova** [comment]
Does this go away if you turn off concurrent world ticking?

**Comment by LunNova** [comment]
This should finally be fixed in 3fd3ffdd48388e2.
