### ISSUE TITLE
Server Deadlock issue (Build #234 - Updated 1/4/2013)

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#6]
It's possible this was fixed in 214 and 215 - but they currently do not allow server start-up so I can't say for sure.

There is a very random deadlock occurring where everything will just completely freeze - no errors, no nothing. The server will need to be killed as it becomes 100% unresponsive.

Sorry but I have no more information then that since it's a deadlock.

**Comment by Puremin0rez** [comment]
Also just to make sure, this commit did not solve this issue - related or not

https://github.com/nallar/TickThreading/commit/c98434f9db20dd4450de498c2e904d9b7f61c9c9

**Comment by LunNova** [comment]
This might be fixed in #216, I'll also implement a watchdog thread so if it does still happen we can see exactly where it's stuck.

**Comment by Puremin0rez** [comment]
Sounds awesome - will test shortly

**Comment by LunNova** [comment]
The watchdog is working, but there are probably still deadlock issues in the current build.

**Comment by Puremin0rez** [comment]
I guess we'll see how many I can catch then - lots of members on my server have been getting more complicated with machines now - perfect scenario. Regardless, I'm still on Build 204 (I think?) and it has been very stable for a few days now.

**Comment by LunNova** [comment]
If you run into a deadlock with #232 it is probably fixed in #233.

**Comment by Puremin0rez** [comment]
I'm assuming I should keep deadlock reports to this issue, but if not - let me know.

This is a deadlock I'm getting on Build #234

http://pastebin.com/uN13biqc

Glancing over it, it appears to be related to Auras from Thaumcraft.

**Comment by LunNova** [comment]
`Current Thread: Server thread
    PID: 14 | Alive: true | State: TIMED_WAITING    Stack:
        java.lang.Thread.sleep(Native Method)
        net.minecraft.server.MinecraftServer.run(MinecraftServer.java:501)
        fy.run(SourceFile:849)`

Looks like it actually wasn't frozen, possibly a bug in the deadlock detector if no players are online? Should be fixed now.

**Comment by Puremin0rez** [comment]
@nallar 

Sounds correct, as I was running my testing server while I tried it out so there wasn't any players :P

**Comment by LunNova** [comment]
and it's probably not fixed in that build, because forge's tick handlers don't seem to run with no players online.

**Comment by Puremin0rez** [comment]
@nallar 

Errr.... that's a little odd.

Must perform workaround surgery! (Creates forge plugin to keep a bot player on at all times)

**Comment by LunNova** [comment]
Actually, I just messed up. Forgot to actually implement .ticks() in ITickHandler. Should be fixed now.

**Comment by Puremin0rez** [comment]
Yep, that particular deadlock has been fixed. Time to find more!

**Comment by Puremin0rez** [comment]
Looks great so far, 10~ players on and no deadlocks thus far... I notice the load is higher in /tps now, is that because its more accurate or because it's just overall more heavier now?

**Comment by LunNova** [comment]
It's more accurate now. Still not 100% accurate, it's hard to measure. Load may also be higher, but I would hope not.

Looking at your server, 76% total load and 2% individual load seems incorrect. I'll look into it.

**Comment by LunNova** [comment]
Seems I checked during a lag spike (backup?). Load's back down to ~10% which makes more sense.

**Comment by Puremin0rez** [comment]
There have been no deadlocks in the last 10~ hours so I'm guessing the frequent ones are gone, or maybe they're all gone!

Will reopen issue when another one is found.
