### ISSUE TITLE
"Wrong Location!" errors - Build 490

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#70]
2013-01-18 20:05:39 [INFO] [STDOUT] Wrong location! px['item.tile.sapling.oak'/2
2672, l='world', x=-32.60, y=88.63, z=245.82]
2013-01-18 20:05:39 [INFO] [STDERR] java.lang.Exception: Stack trace
2013-01-18 20:05:39 [INFO] [STDERR]     at java.lang.Thread.dumpStack(Unknown So
urce)
2013-01-18 20:05:39 [INFO] [STDERR]     at zz.a_nolock(Chunk.java:923)
2013-01-18 20:05:39 [INFO] [STDERR]     at zz.a(Chunk.java)
2013-01-18 20:05:39 [INFO] [STDERR]     at aam.a(AnvilChunkLoader.java:406)
2013-01-18 20:05:39 [INFO] [STDERR]     at aam.a(AnvilChunkLoader.java:103)
2013-01-18 20:05:39 [INFO] [STDERR]     at aam.a(AnvilChunkLoader.java:83)
2013-01-18 20:05:39 [INFO] [STDERR]     at im.f(ChunkProviderServer.java:182)
2013-01-18 20:05:39 [INFO] [STDERR]     at im.c(ChunkProviderServer.java:98)
2013-01-18 20:05:39 [INFO] [STDERR]     at ik.a(SourceFile:65)
2013-01-18 20:05:39 [INFO] [STDERR]     at ik.d(SourceFile:300)
2013-01-18 20:05:39 [INFO] [STDERR]     at gm.d(ServerConfigurationManager.java:
220)
2013-01-18 20:05:39 [INFO] [STDERR]     at iv.a(NetServerHandler.java:410)
2013-01-18 20:05:39 [INFO] [STDERR]     at eb.a(SourceFile:136)
2013-01-18 20:05:39 [INFO] [STDERR]     at cg.b(TcpConnection.java:454)
2013-01-18 20:05:39 [INFO] [STDERR]     at iv.d(NetServerHandler.java:136)
2013-01-18 20:05:39 [INFO] [STDERR]     at iw.b(NetworkListenThread.java:57)
2013-01-18 20:05:39 [INFO] [STDERR]     at ht.b(SourceFile:30)
2013-01-18 20:05:39 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
r(MinecraftServer.java:210)
2013-01-18 20:05:39 [INFO] [STDERR]     at ho.r(DedicatedServer.java:270)
2013-01-18 20:05:39 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
q(MinecraftServer.java:130)
2013-01-18 20:05:39 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.
run(MinecraftServer.java:64)
2013-01-18 20:05:39 [INFO] [STDERR]     at fy.run(SourceFile:849)

**Comment by LunNova** [comment]
Sorry, some issues with world gen up to build 495. It should be fixed now.

**Comment by Puremin0rez** [comment]
It's still happening every little bit, but i'm assuming its the "bugged ones" from the fail builds
