### ISSUE TITLE
Chunk loading is strange - Build #709

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#98]
For some reason, chunks are being very strange in the new build.

Chunks will not load on a teleport until you relog, and sometimes when exploring, chunks wont generate and you will have to walk up to the exact border of where they loaded to get more chunks to load. Relogging will once again, load all the chunks quickly and painlessly. Teleporting is also causing the entire server to lag quite a bit. I'm on an SSD with quite a beefy CPU, so i don't think it's "lag" because this doesn't happen with vanilla.

These things started happening recently, so i'm not sure what caused it.

Default TT Config

**Comment by Puremin0rez** [comment]
Here's an image of what's pretty much happening:
http://i.imgur.com/7rAQX0T.png

Chunks are not loading when teleporting and chunks are loading abnormally slow when walking around.

**Comment by Puremin0rez** [comment]
Sorry for comment spam but I should note this only started happening on the MindCrack v8 releases as far as I can tell.

**Comment by LunNova** [comment]
This should be fixed in the latest build.

**Comment by Puremin0rez** [comment]
@nallar 
The teleporting appears to be fixed, but when traveling, I'm still getting some strange chunk loading patterns.

You'd expect a square loaded around you at all times, but for some reason, it's loading chunks at random and I need to WALK where a chunk would be in order to get it to load, where if I simply disconnect and reconnect, all the chunks will load perfectly within seconds

http://i.imgur.com/i2xucER.jpg
http://i.imgur.com/yc0rS8J.jpg
http://i.imgur.com/KNAzOUT.jpg

It's possible this is Vanilla related bug I'm not too sure.

**Comment by LunNova** [comment]
That does look like normal buggy vanilla rendering, but TT might be making it worse.

If a chunk isn't sent by the server, you see the outline of the chunks next to it. In those images, it's just empty space, meaning that the client hasn't got around to rendering them for some reason.

**Comment by Puremin0rez** [comment]
Yeah, It's like this in Single Player too after some exploration (without TT)

I guess Vanilla will just keep going downhill while we get more important things like god damn Flower Pots.

Thanks nallar :)
